services:
  mysql:
    image: mysql:8.0
    container_name: vallegrande_db
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: vallegrande_db
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3307:3306"
    command: --mysql-native-password=ON
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data:
